<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class CommunicationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
DB::table('communications')->insert([
      'id' => '1',
      'title' => 'Pole to Pole Main Cash Mailing',
      'description' => 'Cash Appeal for the Pole to Pole ship tour.',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '2',
      'ask_id' => '4',
      'start_date' => '43600',
      'end_date' => '43601',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '',
      'user_id' => 1,
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '1',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '2',
      'title' => 'Pole to Pole Main Upgrade Mailing',
      'description' => 'Upgrade Mailing for Pole to Pole',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '2',
      'ask_id' => '6',
      'start_date' => '43600',
      'end_date' => '43601',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '60000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '2',
      'audience_id' => '9',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '3',
      'title' => 'Pole to Pole Reminder Cash Mailing',
      'description' => 'Cash reminder mailing with connect for pole to pole ship tour',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '2',
      'ask_id' => '4',
      'start_date' => '43630',
      'end_date' => '43631',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '3',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '4',
      'title' => 'Pole to Pole Reminder Upgrade Mailing',
      'description' => 'Upgrade reminder mailing with connect for pole to pole ship tour appeal',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '2',
      'ask_id' => '6',
      'start_date' => '43630',
      'end_date' => '43631',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '60000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '4',
      'audience_id' => '9',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '5',
      'title' => 'Pole to Pole Reminder Upgrade SMS',
      'description' => 'Upgrade Reminder SMS for Pole to Pole Ship Tour Appeal',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '4',
      'ask_id' => '6',
      'start_date' => '43644',
      'end_date' => '43645',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '14000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '5',
      'audience_id' => '9',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '6',
      'title' => 'Pole to Pole Reminder Cash SMS',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '4',
      'ask_id' => '4',
      'start_date' => '43644',
      'end_date' => '43645',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '14000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '6',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '7',
      'title' => 'Pole to Pole Main Cash Email 1',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '4',
      'start_date' => '43599',
      'end_date' => '43600',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5bfffade92552d42188a4b90',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '7',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '8',
      'title' => 'Pole to Pole Main Cash Email 2',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '4',
      'start_date' => '43601',
      'end_date' => '43602',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '5bfffb0286d046434c9fa6c4',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '8',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '9',
      'title' => 'Pole to Pole Main Cash Email 3',
      'description' => 'Cash ask for pole to pole ship tour appeal',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '4',
      'start_date' => '43606',
      'end_date' => '43607',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '2',
      'user_id' => 1,
      'trello_id' => '5bfffb63d60c0d5dc68b9df6',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '9',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '10',
      'title' => 'Pole to Pole Main Cash Email 4',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '4',
      'start_date' => '43608',
      'end_date' => '43609',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '3',
      'user_id' => 1,
      'trello_id' => '5bfffb8aabc0e7462e2d83a7',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '10',
      'audience_id' => '8',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '11',
      'title' => 'Pole to Pole Main Upgrade Email 1',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '6',
      'start_date' => '43599',
      'end_date' => '43600',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '60000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5bfffc1e283b540ade7dec18',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '11',
      'audience_id' => '9',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '12',
      'title' => 'Pole to Pole Main Upgrade Email 2',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '6',
      'start_date' => '43601',
      'end_date' => '43602',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '25000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '5bfffc85dce8c0215f5fc057',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '12',
      'audience_id' => '9',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '13',
      'title' => 'DRS deadline reminder',
      'description' => 'Consultation reminder, kick and spread.',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '19',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43591',
      'end_date' => '43592',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1300000',
      'reminder' => '2',
      'user_id' => 1,
      'trello_id' => '5c7fb5dbde356d1b7104d694',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '13',
      'audience_id' => '5',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '14',
      'title' => 'DRS deadline reminder',
      'description' => 'Consultation reminder, kick and spread.',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '19',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43594',
      'end_date' => '43595',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1300000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '5c7fb627131b0f2c366d4304',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '14',
      'audience_id' => '5',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '15',
      'title' => 'Ocean Sanctuaries - email your MP',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '2',
      'start_date' => '43678',
      'end_date' => '43679',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '120000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c812738ac0b6f8955ecd112',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '15',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '16',
      'title' => 'Ocean sanctuaries - email your MP reminder',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '2',
      'start_date' => '43678',
      'end_date' => '43679',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '100000',
      'reminder' => '1',
      'user_id' => 1,
      'trello_id' => '5c8127c7c0dd8d2812e07ddb',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '16',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '17',
      'title' => 'Ocean Sanctuaries - join the PLN 1st wave',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43678',
      'end_date' => '43679',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '20000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c812827abb9395b6aeb22a2',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '17',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '18',
      'title' => 'Ocean sanctuaries - join the PLN 2nd wave email',
      'description' => 'join the PLN (people who have emailed their MP)',
      'basket_id' => '5',
      'area_id' => '13',
      'sub_area_id' => '20',
      'campaign_push_id' => '26',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43678',
      'end_date' => '43679',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '5000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c81288d54e28a7077094a01',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '18',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '19',
      'title' => 'Email MP pledge',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '2',
      'start_date' => '43614',
      'end_date' => '43615',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1000000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c9e07924ab0643c6d72070a',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '19',
      'audience_id' => '1',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '20',
      'title' => 'Spread email MP',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '3',
      'start_date' => '43620',
      'end_date' => '43621',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '100000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c9e07eaaf283422645c44d2',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '20',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '21',
      'title' => 'Rivers: Come to event',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43628',
      'end_date' => '43629',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '200000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c9e083d4a42c516e3dc9c1c',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '21',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '22',
      'title' => 'Rivers: email MP',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '2',
      'start_date' => '43635',
      'end_date' => '43636',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1000000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c9e08ae5800c815c6338c9d',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '22',
      'audience_id' => '1',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '23',
      'title' => 'DD Conversion (Biodiversity)',
      'description' => 'Monthly payday DD conversion email, with biodiversity theme to link in to cash/upgrade appeal content and Unearthed biodiversity explainer videos (launching in April)',
      'basket_id' => '3',
      'area_id' => '6',
      'sub_area_id' => '',
      'campaign_push_id' => '',
      'medium_id' => '1',
      'ask_id' => '5',
      'start_date' => '43616',
      'end_date' => '43617',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '200000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5c9e2ce14feae183054ec6d7',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '23',
      'audience_id' => '6',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '24',
      'title' => 'Berry Cochrane',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '21',
      'medium_id' => '1',
      'ask_id' => '1',
      'start_date' => '43598',
      'end_date' => '43599',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '40000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5cab29e60e13978fb3bcd4b0',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '24',
      'audience_id' => '5',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '25',
      'title' => 'Bonnie Wright Rivers update',
      'description' => 'Email from Bonnie Wright asking supporters to sign the Rivers petition',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '1',
      'start_date' => '43585',
      'end_date' => '43586',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1000000',
      'reminder' => '2',
      'user_id' => 1,
      'trello_id' => '5cab363ce753b539287f4ebe',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '25',
      'audience_id' => '5',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '26',
      'title' => 'Rivers: Kick Bonnie',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '1',
      'start_date' => '43594',
      'end_date' => '43595',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '1000000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5cab36c2d4460581c37c1c0d',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '26',
      'audience_id' => '5',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '27',
      'title' => 'Bio Diversity email series',
      'description' => 'An email to ask people to watch and share UE biodiversity video and sign up for all of them',
      'basket_id' => '3',
      'area_id' => '7',
      'sub_area_id' => '',
      'campaign_push_id' => '',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43586',
      'end_date' => '43587',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '30000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5cab3d155d34e26917effe6c',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '27',
      'audience_id' => '',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '28',
      'title' => 'Rivers Check In at Westminster',
      'description' => '',
      'basket_id' => '5',
      'area_id' => '12',
      'sub_area_id' => '14',
      'campaign_push_id' => '22',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43642',
      'end_date' => '43643',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '200000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5caf178b2c16d203a257b319',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '28',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);
DB::table('communications')->insert([
      'id' => '29',
      'title' => 'ULEZ - questions for the mayor',
      'description' => 'Email to ULEZ consultation signers asking them any questions they have for the mayor ahead of an interview in May.',
      'basket_id' => '6',
      'area_id' => '15',
      'sub_area_id' => '16',
      'campaign_push_id' => '23',
      'medium_id' => '1',
      'ask_id' => '10',
      'start_date' => '43581',
      'end_date' => '43582',
      'date_flexibility' => 'A bit flexible',
      'approx_recipients' => '40000',
      'reminder' => '',
      'user_id' => 1,
      'trello_id' => '5cb5c54491b81f04a01f7a2e',
      'data_selection' => '0',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);   DB::table('communication_audiences')->insert([
      'communication_id' => '29',
      'audience_id' => '4',
      'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
      'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
]);



    }
}
